from enum import Enum


class FlightResultKind(Enum):
    """Enum for the kind of flight result."""

    LOGIN = "LOGIN"
    FLIGHT_SEARCH = "FLIGHT_SEARCH"
    FLIGHT_AVAILABILITIES = "FLIGHT_AVAILABILITIES"
    FLIGHT_PRICING = "FLIGHT_PRICING"
    FLIGHT_RETRIEVE_BY_ID = "FLIGHT_RETRIEVE_BY_ID"
    FLIGHT_RETRIEVE_BY_PNR = "FLIGHT_RETRIEVE_BY_PNR"
    FLIGHT_CANCEL = "FLIGHT_CANCEL"
    FLIGHT_ISSUE = "FLIGHT_ISSUE"
    FLIGHT_COMMISSION_BOOKING = "FLIGHT_COMMISSION_BOOKING"
    FLIGHT_RESERVE = "FLIGHT_RESERVE"
    FLIGHT_BRANDED_FARE_UPSELL = "FLIGHT_BRANDED_FARE_UPSELL"
    FLIGHT_QUEUE_LIST = "FLIGHT_QUEUE_LIST"
